### ISSUE TITLE
Some charts in Chart1Dev have areas with no DataCoverage

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#54] opened 2024-01-27 21:27 UTC
101AA005C1CDE.000 ed4: 
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/6350a1d8-48f8-4fe3-b8d9-370b38a4bb7f)

101AA005C1FOO.000 ed3:
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/554917ab-4cfa-4906-bf78-9257ccc8eb81)

101AA005C1JKL.000 ed2:
![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/82bb4bc2-c511-432f-8141-713837beb278)

101AA005C1HIO.000 ed4:
Most of the chart

101AA005C1WOO.000 ed1:
All the land areas

**Comment by kusala9** [comment] 2024-01-29 12:08
Fixed in new editions of cells in the repository now. If there are any more, raise a separate issues. This was caused by attaching the Data Cvoerage to DepthArea surfaces (which have holes in them for the other group 1). For some reason the converter hadn't created data coverage features for these.??

**Closed by kusala9** 2024-01-29 12:08 UTC
