### ISSUE TITLE
v1.1.0/PowerUp/S100_ROOT/S-101/DATASET_FILES/101AA004X0000.000 contains encoding error

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-164-Sub-Group#18] opened 2023-06-26 16:11 UTC
The subject dataset contains `TidalStreamPanelData` where one of the `tidalStreamValue`.`orientation`.`orientationValue` is set to `" "` (space). This is not valid and prevents the dataset from loading.

`orientationValue` must be empty (null) if unknown, and otherwise must be a real number.

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/9b698b8f-2693-4f2c-86ce-00d6d430f8b2)

**Comment by DavidGrant-NIWC** [comment] 2023-06-26 16:29
* Every `stationName` is set to `Lookinghaven` and every `stationNumber` is `00000`
* The error occurs in feature `1276` - see highlight below (I modified our test bed temporarily to allow this to load).

![image](https://github.com/iho-ohi/S-164-Sub-Group/assets/62906211/534eaab0-8435-4210-9a3e-23b44bb8bdd9)

**Comment by kusala9** [comment] 2023-06-28 13:32
partly a duplicate of  iho-ohi/S-101-Test-Datasets#40 - dataset encoding should be fixed in that repo first, then pulled into the S-164 exchange sets...

**Comment by DavidGrant-NIWC** [comment] 2023-06-28 13:42
Is the intent to address dataset issues in the [S-101 Test Datasets repo](https://github.com/iho-ohi/S-101-Test-Datasets), and to address exchange catalog issues here? I'm (still) confused because this repo has data which is updated more recently than the other repo.

If that is the intent, this repo should only contain the artifacts which are being developed here (CATALOG.XML, CATALOG.SIGN, manual, etc.) and the [releases](https://github.com/iho-ohi/S-164-Sub-Group/releases) should contain the exchange sets developed by pulling the datasets from the other repo and combining them with the contents of this repo. Setting it up this way should help prevent issue duplication, and make it clear what is the authoritative source of each artifact.

**Comment by kusala9** [comment] 2023-07-17 08:26
> Is the intent to address dataset issues in the [S-101 Test Datasets repo](https://github.com/iho-ohi/S-101-Test-Datasets), and to address exchange catalog issues here? I'm (still) confused because this repo has data which is updated more recently than the other repo.
> 
Yes, I believe that is (now) the intent. this repo constructs the exchange set and only holds datasets (and other supporting resources necessary) where they can't be (easily) obtained from elsewhere. I've commented on issue #2 here to this effect as well (and deleted the sample data I initially had in here). How strong/formal should we make the link between the two repositories?

> If that is the intent, this repo should only contain the artifacts which are being developed here (CATALOG.XML, CATALOG.SIGN, manual, etc.) and the [releases](https://github.com/iho-ohi/S-164-Sub-Group/releases) should contain the exchange sets developed by pulling the datasets from the other repo and combining them with the contents of this repo. Setting it up this way should help prevent issue duplication, and make it clear what is the authoritative source of each artifact. It will get difficult when specific changes are necessary from the S-164 point of view and they need to be aggregated with changes also in progress in other repositories...

agree - with this I think. We have constructed PowerUp manually by transferring content from the S-101 repo. Whether we automate this remains to be seen. I'm sure there will be issue duplication but if we link across the repos it should minimise the impact of that. a README.md in the top of an exchange set could be used to record the sources for each dataset. I've also recommended in #2  that the S-101 repo expunge the S-164 name from their folders to avoid further confusion.

One to discuss with S-101PT chair and progress from there.

**Comment by kusala9** [comment] 2023-07-31 13:47
Recommend this is closed as the issue of which repository each dataset is within is now fixed. Much tidying up remains to be done in the S-101 repo but for S-164 the situation is now clear.

**Closed** 2023-10-24 13:43 UTC
Labels: S-101
